// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BookmarksColumns holds the columns for the "bookmarks" table.
	BookmarksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "note", Type: field.TypeString, Size: 1000},
	}
	// BookmarksTable holds the schema information for the "bookmarks" table.
	BookmarksTable = &schema.Table{
		Name:       "bookmarks",
		Columns:    BookmarksColumns,
		PrimaryKey: []*schema.Column{BookmarksColumns[0]},
	}
	// SitesColumns holds the columns for the "sites" table.
	SitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString, Size: 2048},
		{Name: "title", Type: field.TypeString, Size: 100},
	}
	// SitesTable holds the schema information for the "sites" table.
	SitesTable = &schema.Table{
		Name:       "sites",
		Columns:    SitesColumns,
		PrimaryKey: []*schema.Column{SitesColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "count", Type: field.TypeInt, Default: 0},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 100},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// BookmarkTagColumns holds the columns for the "bookmark_tag" table.
	BookmarkTagColumns = []*schema.Column{
		{Name: "bookmark_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// BookmarkTagTable holds the schema information for the "bookmark_tag" table.
	BookmarkTagTable = &schema.Table{
		Name:       "bookmark_tag",
		Columns:    BookmarkTagColumns,
		PrimaryKey: []*schema.Column{BookmarkTagColumns[0], BookmarkTagColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bookmark_tag_bookmark_id",
				Columns:    []*schema.Column{BookmarkTagColumns[0]},
				RefColumns: []*schema.Column{BookmarksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "bookmark_tag_tag_id",
				Columns:    []*schema.Column{BookmarkTagColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// SiteBookmarkColumns holds the columns for the "site_bookmark" table.
	SiteBookmarkColumns = []*schema.Column{
		{Name: "site_id", Type: field.TypeInt},
		{Name: "bookmark_id", Type: field.TypeInt},
	}
	// SiteBookmarkTable holds the schema information for the "site_bookmark" table.
	SiteBookmarkTable = &schema.Table{
		Name:       "site_bookmark",
		Columns:    SiteBookmarkColumns,
		PrimaryKey: []*schema.Column{SiteBookmarkColumns[0], SiteBookmarkColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "site_bookmark_site_id",
				Columns:    []*schema.Column{SiteBookmarkColumns[0]},
				RefColumns: []*schema.Column{SitesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "site_bookmark_bookmark_id",
				Columns:    []*schema.Column{SiteBookmarkColumns[1]},
				RefColumns: []*schema.Column{BookmarksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TagUserColumns holds the columns for the "tag_user" table.
	TagUserColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// TagUserTable holds the schema information for the "tag_user" table.
	TagUserTable = &schema.Table{
		Name:       "tag_user",
		Columns:    TagUserColumns,
		PrimaryKey: []*schema.Column{TagUserColumns[0], TagUserColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_user_tag_id",
				Columns:    []*schema.Column{TagUserColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_user_user_id",
				Columns:    []*schema.Column{TagUserColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserBookmarkColumns holds the columns for the "user_bookmark" table.
	UserBookmarkColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "bookmark_id", Type: field.TypeInt},
	}
	// UserBookmarkTable holds the schema information for the "user_bookmark" table.
	UserBookmarkTable = &schema.Table{
		Name:       "user_bookmark",
		Columns:    UserBookmarkColumns,
		PrimaryKey: []*schema.Column{UserBookmarkColumns[0], UserBookmarkColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_bookmark_user_id",
				Columns:    []*schema.Column{UserBookmarkColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_bookmark_bookmark_id",
				Columns:    []*schema.Column{UserBookmarkColumns[1]},
				RefColumns: []*schema.Column{BookmarksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BookmarksTable,
		SitesTable,
		TagsTable,
		UsersTable,
		BookmarkTagTable,
		SiteBookmarkTable,
		TagUserTable,
		UserBookmarkTable,
	}
)

func init() {
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	BookmarkTagTable.ForeignKeys[0].RefTable = BookmarksTable
	BookmarkTagTable.ForeignKeys[1].RefTable = TagsTable
	SiteBookmarkTable.ForeignKeys[0].RefTable = SitesTable
	SiteBookmarkTable.ForeignKeys[1].RefTable = BookmarksTable
	TagUserTable.ForeignKeys[0].RefTable = TagsTable
	TagUserTable.ForeignKeys[1].RefTable = UsersTable
	UserBookmarkTable.ForeignKeys[0].RefTable = UsersTable
	UserBookmarkTable.ForeignKeys[1].RefTable = BookmarksTable
}
