// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bookmark is the predicate function for bookmark builders.
type Bookmark func(*sql.Selector)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
