// Code generated by ent, DO NOT EDIT.

package bookmark

const (
	// Label holds the string label denoting the bookmark type in the database.
	Label = "bookmark"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSiteID holds the string denoting the site_id field in the database.
	FieldSiteID = "site_id"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// EdgeHaveSite holds the string denoting the have_site edge name in mutations.
	EdgeHaveSite = "have_site"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// Table holds the table name of the bookmark in the database.
	Table = "bookmarks"
	// HaveSiteTable is the table that holds the have_site relation/edge.
	HaveSiteTable = "bookmarks"
	// HaveSiteInverseTable is the table name for the Site entity.
	// It exists in this package in order to avoid circular dependency with the "site" package.
	HaveSiteInverseTable = "sites"
	// HaveSiteColumn is the table column denoting the have_site relation/edge.
	HaveSiteColumn = "site_id"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "bookmarks"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_id"
	// TagsTable is the table that holds the tags relation/edge. The primary key declared below.
	TagsTable = "bookmark_tags"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
)

// Columns holds all SQL columns for bookmark fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldSiteID,
	FieldNote,
}

var (
	// TagsPrimaryKey and TagsColumn2 are the table columns denoting the
	// primary key for the tags relation (M2M).
	TagsPrimaryKey = []string{"bookmark_id", "tag_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NoteValidator is a validator for the "note" field. It is called by the builders before save.
	NoteValidator func(string) error
)
