// Code generated by ent, DO NOT EDIT.

package bookmark

const (
	// Label holds the string label denoting the bookmark type in the database.
	Label = "bookmark"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSiteID holds the string denoting the site_id field in the database.
	FieldSiteID = "site_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// EdgeSite holds the string denoting the site edge name in mutations.
	EdgeSite = "site"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the bookmark in the database.
	Table = "bookmarks"
	// SiteTable is the table that holds the site relation/edge.
	SiteTable = "bookmarks"
	// SiteInverseTable is the table name for the Site entity.
	// It exists in this package in order to avoid circular dependency with the "site" package.
	SiteInverseTable = "sites"
	// SiteColumn is the table column denoting the site relation/edge.
	SiteColumn = "site_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "bookmarks"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for bookmark fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldSiteID,
	FieldTitle,
	FieldNote,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// NoteValidator is a validator for the "note" field. It is called by the builders before save.
	NoteValidator func(string) error
)
